import Head from "next/head";
const Home = () => {
  return (
    <>
      <Head>
        <title>Superdao | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="p-home">Home</section>
    </>
  );
};
export default Home;
